name: kc_113www
description: A new Flutter project for downloading media.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  google_mobile_ads: ^3.0.0
  youtube_explode_dart: ^2.0.0

flutter:
  uses-material-design: true
