name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - run: flutter create . --project-name kc_113www
      - run: sed -i '/defaultConfig {/a \        multiDexEnabled true' android/app/build.gradle
      - run: flutter pub get
      # हमने 'debug' हटाकर 'release' कर दिया है, साइज 150 MB से घटकर ~20 MB हो जाएगा
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
